// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFnLetYw5nC2M2LDCUVVFpF3drNLAsWVA',
    appId: '1:480103045022:web:034ec237dd9fe605dae88f',
    messagingSenderId: '480103045022',
    projectId: 'pet-shop-11ec8',
    authDomain: 'pet-shop-11ec8.firebaseapp.com',
    databaseURL: 'https://pet-shop-11ec8-default-rtdb.firebaseio.com',
    storageBucket: 'pet-shop-11ec8.appspot.com',
    measurementId: 'G-SDLTVP8X1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClKqiDUdHbc-KxKSxLurNKKrLRVo4__yk',
    appId: '1:480103045022:android:ecaaf22839af320fdae88f',
    messagingSenderId: '480103045022',
    projectId: 'pet-shop-11ec8',
    databaseURL: 'https://pet-shop-11ec8-default-rtdb.firebaseio.com',
    storageBucket: 'pet-shop-11ec8.appspot.com',
  );
}
